#include "chartraits.h"

const u8 char_traits[256] = {
    ['0'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,   // '0'..'7' lead octal escapes
    ['1'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['2'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['3'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['4'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['5'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['6'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['7'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,
    ['8'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX,
    ['9'] = CHAR_TRAIT_DECIMAL | CHAR_TRAIT_HEX,

    ['A'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,  ['B'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,
    ['C'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,  ['D'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,
    ['E'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,  ['F'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,
    ['G'] = CHAR_TRAIT_ALPHA, ['H'] = CHAR_TRAIT_ALPHA, ['I'] = CHAR_TRAIT_ALPHA, ['J'] = CHAR_TRAIT_ALPHA,
    ['K'] = CHAR_TRAIT_ALPHA, ['L'] = CHAR_TRAIT_ALPHA, ['M'] = CHAR_TRAIT_ALPHA, ['N'] = CHAR_TRAIT_ALPHA,
    ['O'] = CHAR_TRAIT_ALPHA, ['P'] = CHAR_TRAIT_ALPHA, ['Q'] = CHAR_TRAIT_ALPHA, ['R'] = CHAR_TRAIT_ALPHA,
    ['S'] = CHAR_TRAIT_ALPHA, ['T'] = CHAR_TRAIT_ALPHA, ['U'] = CHAR_TRAIT_ALPHA, ['V'] = CHAR_TRAIT_ALPHA,
    ['W'] = CHAR_TRAIT_ALPHA, ['X'] = CHAR_TRAIT_ALPHA, ['Y'] = CHAR_TRAIT_ALPHA, ['Z'] = CHAR_TRAIT_ALPHA,

    ['a'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,   // \a
    ['b'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,   // \b
    ['c'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,  ['d'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,
    ['e'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX,
    ['f'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_HEX | CHAR_TRAIT_ESCAPE,   // \f
    ['g'] = CHAR_TRAIT_ALPHA, ['h'] = CHAR_TRAIT_ALPHA, ['i'] = CHAR_TRAIT_ALPHA, ['j'] = CHAR_TRAIT_ALPHA,
    ['k'] = CHAR_TRAIT_ALPHA, ['l'] = CHAR_TRAIT_ALPHA, ['m'] = CHAR_TRAIT_ALPHA,
    ['n'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_ESCAPE,                    // \n
    ['o'] = CHAR_TRAIT_ALPHA, ['p'] = CHAR_TRAIT_ALPHA, ['q'] = CHAR_TRAIT_ALPHA,
    ['r'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_ESCAPE,                    // \r
    ['s'] = CHAR_TRAIT_ALPHA,
    ['t'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_ESCAPE,                    // \t
    ['u'] = CHAR_TRAIT_ALPHA,
    ['v'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_ESCAPE,                    // \v
    ['w'] = CHAR_TRAIT_ALPHA,
    ['x'] = CHAR_TRAIT_ALPHA | CHAR_TRAIT_ESCAPE,                    // \x (hex-escape leader)
    ['y'] = CHAR_TRAIT_ALPHA, ['z'] = CHAR_TRAIT_ALPHA,
    ['_'] = CHAR_TRAIT_ALPHA,

    ['"']  = CHAR_TRAIT_ESCAPE | CHAR_TRAIT_PP_BREAK,
    ['\''] = CHAR_TRAIT_ESCAPE | CHAR_TRAIT_PP_BREAK,
    ['?']  = CHAR_TRAIT_ESCAPE,
    ['\\'] = CHAR_TRAIT_ESCAPE | CHAR_TRAIT_PP_BREAK,
    ['\n'] = CHAR_TRAIT_PP_BREAK,
    ['/']  = CHAR_TRAIT_PP_BREAK,   // pp_expand stops here to recognize and strip // and /* comments
};
