#ifndef _LEX_H
#define _LEX_H

#include "../ur/int.h"
#include "../ur/size_t.h"

typedef struct struct_Token {
    u8 tag;
    size_t start;
    size_t limit;
} Token;

// ASSERT: src[len] == 0
Token lex(const u8* src, size_t len, size_t start);

enum {
    TOKEN_EOF ,
    TOKEN_INVALID,
    TOKEN_IDENTIFIER,
    TOKEN_CONSTANT_INT,
    TOKEN_CONSTANT_FLOAT,
    TOKEN_LPAREN,
    TOKEN_RPAREN,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_SEMICOLON,
    TOKEN_TILDE,
    TOKEN_MINUS,
    TOKEN_DECREMENT,
    TOKEN_PLUS,
    TOKEN_ASTERISK,
    TOKEN_SLASH,
    TOKEN_PERCENT,
    TOKEN_AMP,
    TOKEN_PIPE,
    TOKEN_CARET,
    TOKEN_LSHIFT,
    TOKEN_RSHIFT,
    TOKEN_LESS,
    TOKEN_GREATER,
    TOKEN_BANG,
    TOKEN_AND, /* && */
    TOKEN_OR, /* || */
    TOKEN_EQUAL_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_LESS_EQUAL,
    TOKEN_GREATER_EQUAL,
    TOKEN_ASSIGN,
    TOKEN_QUESTION,
    TOKEN_COLON,
    TOKEN_COMMA,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_STRING,
    TOKEN_WIDE_STRING,
    TOKEN_DOT,
    TOKEN_ARROW,
    TOKEN_ELLIPSIS,
    TOKEN_INCREMENT,
    TOKEN_PLUS_ASSIGN,
    TOKEN_MINUS_ASSIGN,
    TOKEN_STAR_ASSIGN,
    TOKEN_SLASH_ASSIGN,
    TOKEN_PERCENT_ASSIGN,
    TOKEN_AMP_ASSIGN,
    TOKEN_PIPE_ASSIGN,
    TOKEN_CARET_ASSIGN,
    TOKEN_LSHIFT_ASSIGN,
    TOKEN_RSHIFT_ASSIGN,

    // KEYWORD (KW) TOKENS
    #define TOKEN_KW_FIRST TOKEN_KW_INT
    TOKEN_KW_INT,
    TOKEN_KW_LONG,
    TOKEN_KW_UNSIGNED,
    TOKEN_KW_SIGNED,
    #define TOKEN_KW_TYPE_LAST TOKEN_KW_SIGNED
    TOKEN_KW_VOID,
    TOKEN_KW_RETURN,
    TOKEN_KW_IF,
    TOKEN_KW_ELSE,
    TOKEN_KW_WHILE,
    TOKEN_KW_DO,
    TOKEN_KW_FOR,
    TOKEN_KW_BREAK,
    TOKEN_KW_CONTINUE,
    TOKEN_KW_STATIC,
    TOKEN_KW_EXTERN,
    TOKEN_KW_GOTO,
    TOKEN_KW_SWITCH,
    TOKEN_KW_CASE,
    TOKEN_KW_DEFAULT,
    TOKEN_KW_VOLATILE,
    TOKEN_KW_CHAR,
    TOKEN_KW_DOUBLE,
    TOKEN_KW_SIZEOF,
    TOKEN_KW_STRUCT,
    TOKEN_KW_UNION,
    TOKEN_KW_REGISTER,
    TOKEN_KW_ASM, /* the GNU __asm__ / __asm spellings */
    TOKEN_KW_TYPEDEF,
    TOKEN_KW_SHORT,
    TOKEN_KW_CONST,
    TOKEN_KW_ENUM,
    TOKEN_KW_INLINE,
    #define TOKEN_KW_LAST TOKEN_KW_INLINE
};

#endif // _LEX_H
